# Generated by Django 5.2 on 2025-04-16 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=63)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=63)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(choices=[('assets', 'Aktywa'), ('liabilities', 'Pasywa'), ('revenue', 'Przychody'), ('expenses', 'Koszty')], max_length=63)),
                ('account_subtype', models.CharField(choices=[('assets', [('fixed', 'Trwałe'), ('current', 'Obrotowe'), ('financial', 'Środki pieniężne'), ('inventories', 'Zapasy'), ('receivables', 'Należności')]), ('liabilities', [('long_term', 'Długoterminowe'), ('short_term', 'Krótkoterminowe'), ('equity', 'Kapitał własny')]), ('revenue', []), ('expenses', [])], max_length=63)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accountancy.book')),
            ],
        ),
    ]
