# Generated by Django 5.2 on 2025-04-21 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountancy', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accountancy.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_subtype',
            field=models.CharField(choices=[('fixed', 'Trwałe'), ('current', 'Obrotowe'), ('financial', 'Środki pieniężne'), ('inventories', 'Zapasy'), ('receivables', 'Należności'), ('long_term', 'Długoterminowe'), ('short_term', 'Krótkoterminowe'), ('equity', 'Kapitał własny')], max_length=63),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='Accountancy.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_transactions', to='Accountancy.account'),
        ),
    ]
