# Generated by Django 4.2.21 on 2025-07-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountancy', '0006_report_book_alter_account_account_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_subtype',
            field=models.CharField(blank=True, choices=[('fixed', 'Trwałe'), ('current', 'Obrotowe'), ('financial', 'Środki pieniężne'), ('inventories', 'Zapasy'), ('receivables', 'Należności'), ('long_term', 'Długoterminowe'), ('short_term', 'Krótkoterminowe'), ('equity', 'Kapitał własny'), ('fixed_incomes', 'Stałe'), ('variable_incomes', 'Zmienne'), ('passive', 'Pasywne'), ('fixed_expenses', 'Stałe'), ('variable_expenses', 'Zmienne'), ('unpredicted', 'Nieprzewidywalne')], max_length=63, null=True),
        ),
    ]
