# Generated by Django 5.2 on 2025-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountancy', '0007_alter_account_account_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='color',
            field=models.CharField(default='#222', max_length=7),
        ),
    ]
