# Generated by Django 5.2 on 2025-09-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountancy', '0008_alter_categories_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='color',
            field=models.CharField(default='#222222', max_length=7),
        ),
    ]
