# Generated by Django 5.2 on 2025-10-04 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountancy', '0010_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accountancy.account'),
        ),
    ]
