# Generated by Django 5.2 on 2025-10-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountancy', '0011_alter_goal_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
